# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 70a7920be8f7ec114a0f3bf61309706dbee005b704bc0bd7d9b994d70bbd84aaa91009ff4e9d68098a7eef392d8ec4a48a94bdabca1f1a865f42c948f9ded39e

test:
  secret_key_base: 8709e87bc12eab49a418ec3de3199a741dbcb21762601f937903b4dafc3eb76089e3d41c99200069cb5ce8f62c0480b47c8149ebb3a99afb6ad99c7d219872ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
